declare function push(url: string): void;
declare function toHome(): void;
declare function toChat(): void;
declare function toMe(): void;
declare function toSearch(platform: string): void;
declare function toLogin(): void;
declare function toCoin(): void;
declare function toNotice(): void;
declare function toPoster(): void;
declare function toAlbum(): void;
declare function toMall(): void;
declare function toCommunity(): void;
declare function toRankList(): void;
declare function back(): void;
declare function loadFail(): void;
declare function toInvoice(params: object): void;
declare function toCalendar(): void;
declare function toTaoBuTingLive(): void;
declare function goToTingCoinPage(): void;
declare const _default: {
    push: typeof push;
    toHome: typeof toHome;
    toChat: typeof toChat;
    toMe: typeof toMe;
    toCoin: typeof toCoin;
    toSearch: typeof toSearch;
    toNotice: typeof toNotice;
    toPoster: typeof toPoster;
    toAlbum: typeof toAlbum;
    toMall: typeof toMall;
    toCommunity: typeof toCommunity;
    toRankList: typeof toRankList;
    back: typeof back;
    loadFail: typeof loadFail;
    toInvoice: typeof toInvoice;
    toLogin: typeof toLogin;
    toCalendar: typeof toCalendar;
    toTaoBuTingLive: typeof toTaoBuTingLive;
    goToTingCoinPage: typeof goToTingCoinPage;
};
export default _default;
